[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
# Phase 4A: Health monitoring configuration
port = 8000

[environments.production]
variables = { HEALTH_PORT = "8000", ENVIRONMENT = "production" }