[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python start.py"
# Configuration Health Check optimisée pour UptimeRobot
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
# Phase 4A + 4C: Health monitoring avec résilience
port = 8000

[environments.production]
variables = { 
    HEALTH_PORT = "8000", 
    ENVIRONMENT = "production",
    ENABLE_HEALTH_MONITOR = "true",
    HEALTH_CHECK_INTERVAL = "300"
}

# Configuration UptimeRobot optimisée
[railway.uptime]
# Railway ping interne toutes les minutes
internal_check_interval = 60
# Health check externe pour UptimeRobot
external_endpoints = [
    "/health",           # Endpoint basique pour Railway
    "/health/detailed",  # Endpoint détaillé pour monitoring avancé
    "/health/resilience" # Endpoint de résilience Phase 4C
]

# Configuration de monitoring avancé
[railway.monitoring]
enable_metrics = true
log_retention = "7d"
alert_thresholds = {
    response_time_ms = 5000,
    error_rate_percent = 5,
    memory_usage_percent = 90
}